AllCops:
  NewCops: enable
  Exclude:
    - .irbrc
    - config.ru
    - bin/**/*
    - config/initializers/appoptics_apm.rb
    - tmp/*.rb
    - db/data/*.rb
    - db/migrate/*.rb
    - db/schema.rb
    - db/seeds.rb
    - spec/teaspoon_env.rb
    - tmp/*.rb
    - vendor/**/*
    - node_modules/**/*

##########

# Layout #

Layout/ArrayAlignment:
  Enabled: true
  Exclude:
    - config/environments/*.rb

Layout/HashAlignment:
  Exclude:
    - config/routes.rb
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Exclude:
    - config/routes.rb
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/simple_form.rb
    - db/migrate/*.rb
    - spec/**/*

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

##########

# Lint #

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/ElseLayout:
  Enabled: false

Lint/FlipFlop:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/InheritException:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Lint/LiteralInInterpolation:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RequireParentheses:
  Enabled: false

Lint/SafeNavigationWithEmpty:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Lint/Void:
  Enabled: false

##########

# Metrics #

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

##########

# Naming #

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

##########

# Style #

Style/Alias:
  Enabled: false

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLambdaParameter:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Encoding:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - db/migrate/*.rb

# These next two Hash cops seem to change the functionality of
# the code so tread lightly if you turn them on.
Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()
    '%i': ()
    '%': '{}'

Style/PerlBackrefs:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - config/initializers/simple_form.rb
    - db/migrate/*.rb

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
